name: Deploy Documentation

on:
  push:
    branches: [ main ]
    paths: [ 'docs/**', 'backend/**', '.github/workflows/docs.yml' ]
  pull_request:
    branches: [ main ]
    paths: [ 'docs/**', 'backend/**', '.github/workflows/docs.yml' ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocstrings[python] mkdocs-material

      - name: Install spaCy model
        run: |
          python -m spacy download en_core_web_sm

      - name: Build documentation
        run: |
          cd docs
          mkdocs build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs/site'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 